- platform: aqualogic
  monitored_conditions:
    - aux_1
    #- aux_2
    #- aux_3
    #- aux_4
    #- aux_5
    #- aux_6
    #- aux_7
    #- aux_8
    #- aux_9
    #- aux_10
    #- aux_11
    #- aux_12
    #- aux_13
    #- aux_14
    - filter
    #- filter_low_speed
    #- heater_1
    #- heater_auto_mode
    - left
    - lights
    - menu
    - minus
    #- pool
    - plus
    - right
    - service
    #- spa
    - super_chlorinate
    #- valve_3
    #- valve_4